new function publishChildren
BonnierNews/b0rker pull request #57
Opened 2024-01-31 10:48 UTC by johark

2024-01-31 10:56 UTC, MattiasOlla requested changes
Är det inte `publishMessagesBulk` du vill använda?

2024-01-31 11:49 UTC, MattiasOlla approved these changes
Glöm inte att bumpa versionen i `package.json` och `package-lock.json`

2024-01-31 11:49 UTC, MattiasOlla commented on lib/publish-message.js
> +export async function publishChildren(messages) {
```suggestion
export async function publishBulkWithIndividualAttributes(messages) {
```

2024-04-23 09:06 UTC, johark commented
Old code, closing PR 👴

2024-04-23 09:06 UTC, closed without merging